version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sentry/sentry-laravel
    versions:
    - 2.4.1
  - dependency-name: laravel/framework
    versions:
    - 8.30.1
    - 8.31.0
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: backbone.marionette
    versions:
    - ">= 4.a, < 5"
  - dependency-name: bootstrap
    versions:
    - ">= 4.a, < 5"
  - dependency-name: "@sentry/browser"
    versions:
    - ">= 5.a, < 6"
  - dependency-name: "@sentry/browser"
    versions:
    - 6.0.2
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.2.0
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.3.0
    - 6.3.1
  - dependency-name: webpack
    versions:
    - 5.24.3
    - 5.24.4
    - 5.34.0
  - dependency-name: css-loader
    versions:
    - 5.1.2
