checks:
    php:
        code_rating: true

filter:
    excluded_paths:
        - 'bootstrap/'
        - 'config/'
        - 'database/'
        - 'tests/'
        - 'vendor/'

imports:
    - javascript
    - php

tools:
    external_code_coverage:
        runs: 2
        timeout: 1800

