checks:
    php:
        code_rating: true

filter:
    excluded_paths:
        - 'vendor/*'
        - 'config/*'
        - 'tests/'

imports:
    - javascript
    - php

tools:
    external_code_coverage:
        runs: 3
        timeout: 3600

