sudo: required
dist: trusty
language: php
php:
    - 7
    - 7.1

addons:
    mariadb: "10.0"

cache:
    directories:
    - "$HOME/.composer/cache/files"
    - "$HOME/.npm"
    - "$HOME/.cache/bower"

matrix:
    fast_finish: true

branches:
   only:
   - master
   - production

before_script:
    # Install yarn
    - npm install -g yarn

    # Install dependencies
    - make install-deps

    # Set up DB
    - mysql -u root -e 'create database weinstein_test;'
    - mysql -u root -e "CREATE USER 'weinstein_test'@'localhost' IDENTIFIED BY 'test';"
    - mysql -u root -e "GRANT SUPER on *.* to 'weinstein_test'@'localhost';"
    - mysql -u root -e "GRANT ALL PRIVILEGES ON weinstein_test.* TO 'weinstein_test'@'localhost';"

    # Copy environment file
    - cp tests/test.env .env
    - cat .env

script:
    - ./node_modules/grunt-cli/bin/grunt

    # Check PHP syntax
    - find . -name \*.php -not -path './vendor/*' -exec php -l "{}" \;

    # Generate secure key
    - rm bootstrap/cache/compiled.php
    - php artisan key:generate --no-interaction
    - cat .env

    # Prepare DB - rollback once to catch potential migration/rollback errors
    - php artisan migrate --no-interaction
    - php artisan migrate:rollback --no-interaction
    - php artisan migrate --no-interaction

    # Test PHP
    - make test

    # Upload coverage results to scrutinizer
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover tests/clover.xml

after_script:
    - cat storage/logs/laravel.log

after_success:
    - ./build/docker-images.sh

