sudo: required
dist: trusty
language: php
php:
    - 5.6
    - 7

cache:
    directories:
      - "$HOME/.composer/cache/files"

matrix:
    fast_finish: true

before_install:
    - phpenv config-rm xdebug.ini

before_script:
    - composer install --dev
script:
    - phpunit -c tests/phpunit.xml
