sudo: required
dist: trusty
language: php
php:
    - 5.6
    - 7

addons:
    apt:
      packages:
        - mysql-server-5.6
        - mysql-client-core-5.6
        - mysql-client-5.6

cache:
    directories:
      - "$HOME/.composer/cache/files"

matrix:
    fast_finish: true

before_install:
    - phpenv config-rm xdebug.ini

before_script:
    - composer install --dev

    # Set up DB
    - mysql -u root -e 'create database weinstein_test;'
    - mysql -u root -e "CREATE USER 'weinstein_test'@'localhost' IDENTIFIED BY 'test';"
    - mysql -u root -e "GRANT SUPER on *.* to 'weinstein_test'@'localhost';"
    - mysql -u root -e "GRANT ALL PRIVILEGES ON weinstein_test.* TO 'weinstein_test'@'localhost';"

script:
    # Generate secure key
    - php artisan key:generate

    # Prepare DB
    - php artisan migrate

    # Test PHP
    - phpunit -c tests/phpunit.xml
